### PR TITLE
Minor provisioning fixes

### PR DESCRIPTION
**Pull request by vfebvre**

### CODE REVIEW

**Comment by agrare** [comment]
>  Do you know how to disable this functionality "Clone selected Template" for the time being ?

@kavyanekkalapu do you know if the UI is checking any supports feature for this?  It is hard for me to tell from the UI code I've found in https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/helpers/application_helper/toolbar/template_infras_center.rb#L142

**Comment by kavyanekkalapu** [comment]
> > Do you know how to disable this functionality "Clone selected Template" for the time being ?
> 
> @kavyanekkalapu do you know if the UI is checking any supports feature for this? It is hard for me to tell from the UI code I've found in https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/helpers/application_helper/toolbar/template_infras_center.rb#L142

@vfebvre It doesn't look like it. you can see example and documentation of how to disable toolbar button.

**Example:** Use klass
https://github.com/ManageIQ/manageiq-ui-classic/blob/db6274f318a6b12bad005592013e838f05d754e3/app/helpers/application_helper/toolbar/user_center.rb#L19

https://github.com/ManageIQ/manageiq-ui-classic/blob/db6274f318a6b12bad005592013e838f05d754e3/app/helpers/application_helper/button/rbac_user_copy.rb#L1

**Doc link**
https://github.com/ManageIQ/guides/blob/master/providers/create_operation.md

**Comment by vfebvre** [comment]
For the UI issue, created a separate PR: https://github.com/ManageIQ/manageiq-ui-classic/pull/8108

**Review by jaywcarman — APPROVED** [review]
LGTM

**Pull request merged**
